Repository astropy/astropy-helpers, pull requests merged in 2018-12, with the labels that each got.

#427 Check that docs are generated in the correct location
  astropy_helpers/tests/test_setup_helpers.py
Labels: Ready-for-final-review, no-changelog-entry-needed

#428 Fix docs build with Sphinx 1.8+
  CHANGES.rst
  astropy_helpers/commands/build_sphinx.py
  astropy_helpers/tests/test_setup_helpers.py
Labels: Docs, Ready-for-final-review, bug, merge-when-ci-passes

#430 Remove unused sys.append
  astropy_helpers/tests/test_setup_helpers.py
Labels: merge-when-ci-passes, no-changelog-entry-needed, testing

#431 Further fix for Sphinx 1.8+
  astropy_helpers/commands/build_sphinx.py
Labels: no-changelog-entry-needed

#433 Fix get_compiler_option import
  astropy_helpers/openmp_helpers.py
Labels: no-changelog-entry-needed
