Repository astropy/astropy-helpers, pull requests merged in 2018-05, with the labels that each got.

#391 Remove ez_setup.py from MANIFEST
  MANIFEST.in
Labels: no-changelog-entry-needed

#393 Use intersphinx of released version rather than dev
  astropy_helpers/sphinx/conf.py
Labels: bug, merge-when-ci-passes, no-changelog-entry-needed

#394 Fix backport for minimum python version
  ah_bootstrap.py
Labels: Affects-dev, merge-when-ci-passes
