Repository astropy/astropy-helpers, pull requests merged in 2018-11, with the labels that each got.

#414 Switch to codecov for coverage reporting
  .coveragerc
  .travis.yml
  appveyor.yml
Labels: Ready-for-final-review, no-changelog-entry-needed, testing

#413 Simplify build_docs command to avoid patching code from Sphinx
  CHANGES.rst
  astropy_helpers/commands/build_sphinx.py
  astropy_helpers/tests/__init__.py
  astropy_helpers/tests/test_setup_helpers.py
Labels: Ready-for-final-review

#425 Using deprecated imp rather than importlib for python2 compatibility
  astropy_helpers/tests/test_setup_helpers.py
Labels: no-changelog-entry-needed, testing

#416 Added initial docs about what the package does
  CHANGES.rst
  README.rst
Labels: Ready-for-final-review, merge-when-ci-passes

#424 Change deprecated importlib usage
  astropy_helpers/tests/test_setup_helpers.py
Labels: no-changelog-entry-needed
