Repository astropy/astropy-helpers, pull requests merged in 2019-06, with the labels that each got.

#482 Remove deprecation warning for build_sphinx
  CHANGES.rst
  astropy_helpers/commands/build_sphinx.py
  astropy_helpers/tests/test_setup_helpers.py
Labels: sphinx

#485 Fix inclusion of compiler.c in tar file
  .travis.yml
  CHANGES.rst
  setup.cfg
Labels: merge-when-ci-passes

#488 Fix error that occurred when using bare pytest in packages that use astropy-helpers
  CHANGES.rst
  astropy_helpers/commands/_dummy.py
Labels: bug

#489 Remove future imports
  astropy_helpers/commands/build_sphinx.py
  astropy_helpers/openmp_helpers.py
  astropy_helpers/setup_helpers.py
  astropy_helpers/tests/test_ah_bootstrap.py
  astropy_helpers/utils.py
  astropy_helpers/version_helpers.py
Labels: cleanup, no-changelog-entry-needed

#490 Correcty typo in error message
  astropy_helpers/commands/build_sphinx.py
Labels: no-changelog-entry-needed
