Repository astropy/astropy-helpers, pull requests merged in 2019-04, with the labels that each got.

#457 Remove PY2 configparser import
  ah_bootstrap.py
Labels: cleanup, no-changelog-entry-needed

#458 adding sphinx-dev testing to the cron jobs
  .travis.yml
Labels: no-changelog-entry-needed, testing

#464 Make sure we directly install mpl for py3.5
  .gitignore
  .travis.yml
  astropy_helpers/commands/build_sphinx.py
Labels: merge-when-ci-passes, no-changelog-entry-needed, testing

#466 OPENMP_EXPECTED defaults to False silently
  astropy_helpers/tests/test_openmp_helpers.py
Labels: no-changelog-entry-needed

#468 Ignore .coverage.subprocess
  .gitignore
Labels: no-changelog-entry-needed

#470 TST: Delete temp file when not needed
  astropy_helpers/tests/test_setup_helpers.py
Labels: no-changelog-entry-needed, testing

#465 Workaround numpydoc new sphinx requirement
  .travis.yml
  astropy_helpers/commands/build_sphinx.py
Labels: merge-when-ci-passes, no-changelog-entry-needed

#473 Rename readthedocs.yml to .readthedocs.yml
  .readthedocs.yml
Labels: no-changelog-entry-needed
