Repository astropy/astropy-helpers, pull requests merged in 2019-01, with the labels that each got.

#437 Use raw string in regex
  ah_bootstrap.py
Labels: no-changelog-entry-needed

#440 Simplify API for register_commands and generate_version_py
  .travis.yml
  CHANGES.rst
  README.rst
  ah_bootstrap.py
  astropy_helpers/setup_helpers.py
  astropy_helpers/tests/test_git_helpers.py
  astropy_helpers/tests/test_setup_helpers.py
  astropy_helpers/version_helpers.py
Labels: enhancement

#444 Move documentation to Sphinx
  .circleci/config.yml
  .gitignore
  CHANGES.rst
  README.rst
  astropy_helpers/git_helpers.py
  astropy_helpers/setup_helpers.py
  astropy_helpers/version_helpers.py
  docs/Makefile
  docs/advanced.rst
  docs/api.rst
  docs/basic.rst
  docs/conf.py
  docs/developers.rst
  docs/index.rst
  docs/known_issues.rst
  docs/make.bat
  docs/updating.rst
  docs/using.rst
  readthedocs.yml
  setup.py
Labels: Ready-for-final-review, enhancement

#445 Moved most of the setup.py configuration to setup.cfg
  .travis.yml
  CHANGES.rst
  ah_bootstrap.py
  astropy_helpers/commands/setup_package.py
  setup.cfg
  setup.py
Labels: Ready-for-final-review, enhancement

#443 Create setup() wrapper that does all the standard astropy-helpers actions
  CHANGES.rst
  astropy_helpers/setup_helpers.py
  astropy_helpers/tests/test_git_helpers.py
  astropy_helpers/tests/test_setup_helpers.py
  docs/basic.rst
Labels: Ready-for-final-review, enhancement

#447 Remove code from astropy_helpers.utils that isn't used
  CHANGES.rst
  astropy_helpers/utils.py
Labels: cleanup

#449 Remove mention of get_entry_points which isn't actually implemented
  astropy_helpers/setup_helpers.py
  docs/basic.rst
Labels: no-changelog-entry-needed

#446 Simplify custom build_ext
  CHANGES.rst
  astropy_helpers/commands/build_ext.py
  astropy_helpers/distutils_helpers.py
  astropy_helpers/setup_helpers.py
  astropy_helpers/utils.py
Labels: cleanup
