Repository astropy/astropy-helpers, pull requests merged in 2019-05, with the labels that each got.

#475 Removing sphinx extension that works around old bug
  astropy_helpers/sphinx/conf.py
  astropy_helpers/sphinx/ext/tocdepthfix.py
Labels: merge-when-ci-passes, upstream

#474 Remove auto installing sphinx astropy
  .travis.yml
  CHANGES.rst
  appveyor.yml
  astropy_helpers/commands/build_sphinx.py
Labels: Docs, sphinx, upstream

#478 Update sphinx-automodapi to v0.11
  CHANGES.rst
  astropy_helpers/extern/automodapi/__init__.py
  astropy_helpers/extern/automodapi/automodapi.py
  astropy_helpers/extern/automodapi/automodsumm.py
  astropy_helpers/extern/automodapi/smart_resolver.py
Labels: merge-when-ci-passes, sphinx

#479 Fix readme so it can be rendered in pypi
  README.rst
Labels: Documentation, no-changelog-entry-needed

#480 Remove PY2 compat for C compiler
  astropy_helpers/commands/src/compiler.c
  astropy_helpers/tests/test_setup_helpers.py
Labels: cleanup, merge-when-ci-passes, no-changelog-entry-needed
