Repository astropy/astropy-helpers, pull requests merged in 2019-02, with the labels that each got.

#451 Write error messages on stderr
  ah_bootstrap.py
  astropy_helpers/setup_helpers.py
  astropy_helpers/version_helpers.py
  setup.py
Labels: Affects-dev, no-changelog-entry-needed

#452 Fix build_ext in case where Cython is not available but required and installed via setup_requires
  astropy_helpers/commands/build_ext.py
Labels: Affects-dev, bug

#454 Updating bundled sphinx extensions to match sphinx-astropy 1.1.1
  CHANGES.rst
  astropy_helpers/sphinx/ext/changelog_links.py
  astropy_helpers/sphinx/ext/tests/__init__.py
Labels: sphinx
